.\" thought (BRAIN)
.\" Copyright (C) 2012-2013 Joshua Hawcroft
.\" License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.\" This is free software: you are free to change and redistribute it.
.\" There is NO WARRANTY, to the extent permitted by law.
.TH thought 1 "October 2013" JOX "BRAIN Manuals"
.LO 1
.SH NAME
thought \- start a BRAIN thought
.SH SYNOPSIS
.B thought
.R [ options ]
.RB name
.RB ...
.SH DESCRIPTION
.B thought
initiates a BRAIN 'thought'; it executes a script or program with the specified
.I name\fR.  Any arguments following \fIname\fR are passed to the specified script or program.

By default, 
.B thought
looks for 
.I name
in the configured thoughts directory (see
.BR brain.conf (1).)  
If
.I name
contains a slash (/) then 
.B thought
interprets it as a file specification, so that you can do 
.B thought ./thirsty
or even\f
.B thought /home/josh/thoughts/make-cuppa\fR.

The process runs in the background and output from the script or program is redirected to the thought log file (see
.BR brain.conf (1).)
.SH OPTIONS
.TP
.B \-d\fR or \fB\-\-debug
Causes process output to be directed to the screen (\fBstandard output\fR) rather than sent to the log file.
The process runs in the foreground.
.TP
.B \-t\fR or \fB\-\-timeout " seconds"
Overrides the default timeout (15 seconds) for process execution. Specifying any value less than 2 causes 
.B thought\fR to use the default.
.TP
.B \-v\fR or \fB\-\-version
Print \fBthought\fR version information and exit.
.TP
.B \-h\fR or \fB\-\-help
Print help text and exit.
.SH ENVIRONMENT
Environment variables are passed to the script or program verbatim.
.SH NOTES
If a process timeout occurs, the process will be sent \fBSIGKILL\fR and terminated immediately.  The log will contain the text 

  Thought took too long and was aborted.
.SH SEE ALSO
brain.conf(1)
